# Generated by Django 5.1.4 on 2025-01-04 09:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bloghashtagmodel',
            options={'verbose_name': 'blog hashtag', 'verbose_name_plural': 'blog hashtags'},
        ),
    ]
