# Generated by Django 5.1.4 on 2025-01-04 10:31

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0004_blogcommentmodel_comment'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='bloglikemodel',
            unique_together={('blog', 'user')},
        ),
    ]
